.TH freightproxy "1" "Apr 2015" "Neil Horman"
.SH NAME
freightproxy \- Control utility to manage freight-agent database 
.SH SYNOPSIS
\fBfrieghtproxy [options] 
.SH DESCRIPTION
.B freightproxy
Is a xml-rpc server designed to allow proxied communication to a freight database from the outsside world 
.SH OPTIONS
.TP
\fB freightproxy [OPTIONS] 
.TP
.B -h | --help
Display options and usage for the daemon 
.TP
.B -c | --config </path/to/config/file>
Specify the config file to use with freightproxy (defaults to /etc/freight/config)
.SH CONFIG FILE
see the freight-agent man page for config file details

