.TH freight-network-config "1" "Apr 2015" "Neil Horman"
.SH NAME
freight-network-config - Configuration file format for freight networks
.B 
.SH CONFIG FILE FORMAT

The network config file has the following format

.nf
---------------------------------------------
# These are comments


# The leading config block starts with network= 
network = {
        type = "<network type>";
};

address_config = {
	ipv4_aquisition = "dhcp";
	ipv6_aquisition = "dhcpv6|slaac";
};

<type>_config = {
	# see network type sections for config options
};


.SH NETWORK TYPES


.B bridged
.P
Bridged networks are just that, simple straight layer 2 bridges.  Freight nodes
running containers attached to networks of this type will create a bridge,
attach a physical interface to the bridge, create a veth pair, attach one end to
the bridge and pass the other end to the container.


.SH ADDRESS CONFIG
The address config section ennumerates how a container on this network will
obtain an address.  Current supported formats are dhcp, and slaac

.SH NETWORK TYPE CONFIGURATIONS
.B bridged_config
.P
There are no bridge specific config options


