.TH freight-network-config "1" "Apr 2015" "Neil Horman"
.SH NAME
freight-network-config - Configuration file format for freight networks
.B 
.SH CONFIG FILE FORMAT

The network config file has the following format

.nf
---------------------------------------------
# These are comments


# The leading config block starts with network= 
network = {
        type = "<network type>";
};

address_config = {
	ipv4_aquisition = "none|dhcp|external_static";
	ipv6_aquisition = "none|dhcpv6|slaac|external_static";
};

<type>_config = {
	# see network type sections for config options
};

ipv4_static_config = {
	addr_start = "192.168.1.2";
	addr_end = "192.168.1.254";
	netmask = "255.255.255.0";
	dns = "192.168.1.1";
	defroute = "192.168.1.1";
};

ipv6_static_config = {
	addr_start = "2001:470:8:a08::0:1";
	addr_end = "2001:470:8:a08::0:ffff";
	netmask = "/64";
	dns = "2001:470:8:a08:7aac:c0ff:fec2:933b";
	defroute = "fe80::12c3:7bff:fe42:d970";
};
	

.SH NETWORK TYPES


.B bridged
.P
Bridged networks are just that, simple straight layer 2 bridges.  Freight nodes
running containers attached to networks of this type will create a bridge,
attach a physical interface to the bridge, create a veth pair, attach one end to
the bridge and pass the other end to the container.


.SH ADDRESS CONFIG
The address config section ennumerates how a container on this network will
obtain an address.  Current supported formats are dhcp, slaac, and external_static

.B dhcp
.P
The container will have its config modified to run dhclient on network activiation
.P
.B slaac
.P
The container will have its config modified to use slaac to obtain an ipv6 address
.P
.B external_static
.P
Freight will allocate an address for the container using the static address
configuration for the network, and then modify the container to use that address
as a static configuration


.SH NETWORK TYPE CONFIGURATIONS
.B bridged_config
.P
There are no bridge specific config options


.SH STATIC CONFIGURATION
.P
The Ipv4/6 static configuration section are for use with the external_static
aquisition type.  This address assignment type has the freight agent allocate a
network address on behalf of the container and assign it in a static fashion.
The configuration defines the allocatable address range for the network and the
static dns/default route configuration for containers attached to the network

