.TH freight-agent "1" "Apr 2015" "Neil Horman"
.SH NAME
freight-agent \- daemon to download and execute systemd containers 
.SH SYNOPSIS
\fBfrieght-agent [options]
.SH DESCRIPTION
.B freight-agent
Is a daemon that executes on a remote host, downloading and executing systemd
containers produced by freight-builder.  A freight administrator can direct
configured agents to execute containers provided in configured yum repositories.
.SH OPTIONS
.TP
\fB freight-agent [OPTIONS] 
.TP
.B -h | --help
Display options and usage for the daemon 
.TP
.B -c | --config </path/to/config/file>
Specify the config file to use with freight-agent (defaults to
.TP
.B -l | --list <all|local|running>
Select local or global scope in list mode, or list running containers
.TP
.B -v | --verbose
Verbose output
.TP
.B -m | --mode <mode>
Specify the mode which freight agent is operating in
.TP
.B --mode node
Operate in node mode - freight-agent listens for and executes container requests
.TP
.B --mode scheduler 
Operate in scheduler mode - freight-agent schedules containers for freightctl and monitors node health
.TP
.B --mode init
Preform a one time initalization of the container working directory for
freight-agent.  This is useful for setting up for local container install and
execution.
.TP
.B --mode clean
Remove that freight-agent container root working directory.  This destroys the
yum and local rpm databases that track which containers are installed, removes
the installed containers, and destroys the existing config retrieved from the
database.
.TP

.SH CONFIG FILE FORMAT 

The config file has the following format 

.nf
---------------------------------------------
# These are comments


# The type of database to connect to
# postgres is meant for clusters of freight agents on multiple systesm
# sqlite is meant for local installations 
# freightproxy is the xmlrpc proxy to a backend postgres db
db = {
	dbtype = "postgres | sqlite | freightproxy";
	hostaddr = "hostname of db server";
	hostport = "optional port of db server
	dbname = "Name of database/database file";
	user = "User name to access server";
	password = "password to access server";
};


# configuration for freight-agent when running in node mode
node = {
	container_root = "Path to container store";
	host_bridge = "bridge to use for container communication";
	hostname = "name to register in db. defaults to gethostname";
};

# configuration for freight proxy server
proxy = {
        serverport = "8080";
        log = "/tmp/freightproxy.log";
};

master = {
};

----------------------------------------------
.fi


.TP
Note that the dbtype field supports the following database types
.TP
.B postgres
.P
Standard postgres database
.TP
.B nodb
.P
A Null db for local freigght agent use
.TP
.B freightproxy
.P
Connection to the freightproxy xmlrpc database proxy

