#!/bin/sh
# Hack to get around sysfs oddities
# sysfs is mounted but reflects the init namespace
# We also need sysfs to reflect the container namespace

# To do the above, crate a new mount point
mkdir $FREIGHT_CONTAINERFS/csys

# Then we need to modify the network-function script to use this location
sed -i -e"s/\/sys\//\/csys\//g" $FREIGHT_CONTAINERFS/etc/sysconfig/network-scripts/network-functions
sed -i -e"s/\/sys\//\/csys\//g" $FREIGHT_CONTAINERFS/etc/sysconfig/network-scripts/ifup-eth

# We also need to modify the script to remove the @dev garbage which is meaningless in a container
sed -i -e"s/\(.*ip -o link |.*\)/\1 | sed -e\"s\/@.*\/\/\"/" $FREIGHT_CONTAINERFS/etc/sysconfig/network-scripts/network-functions


# Then touch /etc/sysconfig/network so the network service will function properly
touch $FREIGHT_CONTAINERFS/etc/sysconfig/network

cat >> $FREIGHT_CONTAINERFS/post_install << EOF

setfiles /etc/selinux/targeted/contexts/files/file_contexts /

#We need to setup the root password
echo redhat | passwd -f --stdin root

#Then we need to enable the web server
systemctl enable httpd

#And General networking
systemctl enable network

#Hack to setup fstab to mount contaienr sysfs properly
cp /etc/filesystems /etc/fstab
sed -i -e"1i \nodev	\/csys	sysfs	defaults	0 0" -e"1,$ d" /etc/fstab

EOF

chmod 755 $FREIGHT_CONTAINERFS/post_install

cd $FREIGHT_CONTAINERFS

chroot . /post_install

rm -f $FREIGHT_CONTAINERFS/post_install


